wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1655169678
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      4: 3.9.13
      5: 0.12.18
      8:
      - 1
      - 4
      - 5
      10:
      - 9
